[package]
name = "icndb"
version = "0.2.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
hyper = "*"
hyper-native-tls = { version = "*", optional = true }
serde = "*"
serde_derive = "*"
serde_json = "*"

[features]
default = ["ssl"]
ssl = ["hyper-native-tls"]
