[package]
name = "icndb"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
hyper = {version = "0.9", default-features = false}
rustc-serialize = "*"

[features]
default = ["ssl"]
ssl = ["hyper/ssl"]
